// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/czh0526/aries-framework-go/spi/storage (interfaces: Provider,Store)
//
// Generated by this command:
//
//	mockgen -destination pkg/internal/gomocks/spi/storage/mocks.gen.go -self_package mocks -package mocks github.com/czh0526/aries-framework-go/spi/storage Provider,Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storage "github.com/czh0526/aries-framework-go/spi/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProvider)(nil).Close))
}

// GetOpenStores mocks base method.
func (m *MockProvider) GetOpenStores() []storage.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenStores")
	ret0, _ := ret[0].([]storage.Store)
	return ret0
}

// GetOpenStores indicates an expected call of GetOpenStores.
func (mr *MockProviderMockRecorder) GetOpenStores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenStores", reflect.TypeOf((*MockProvider)(nil).GetOpenStores))
}

// GetStoreConfig mocks base method.
func (m *MockProvider) GetStoreConfig(name string) (storage.StoreConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreConfig", name)
	ret0, _ := ret[0].(storage.StoreConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreConfig indicates an expected call of GetStoreConfig.
func (mr *MockProviderMockRecorder) GetStoreConfig(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreConfig", reflect.TypeOf((*MockProvider)(nil).GetStoreConfig), name)
}

// OpenStore mocks base method.
func (m *MockProvider) OpenStore(name string) (storage.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenStore", name)
	ret0, _ := ret[0].(storage.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenStore indicates an expected call of OpenStore.
func (mr *MockProviderMockRecorder) OpenStore(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenStore", reflect.TypeOf((*MockProvider)(nil).OpenStore), name)
}

// SetStoreConfig mocks base method.
func (m *MockProvider) SetStoreConfig(name string, config storage.StoreConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoreConfig", name, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStoreConfig indicates an expected call of SetStoreConfig.
func (mr *MockProviderMockRecorder) SetStoreConfig(name, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoreConfig", reflect.TypeOf((*MockProvider)(nil).SetStoreConfig), name, config)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Batch mocks base method.
func (m *MockStore) Batch(operations []storage.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Batch", operations)
	ret0, _ := ret[0].(error)
	return ret0
}

// Batch indicates an expected call of Batch.
func (mr *MockStoreMockRecorder) Batch(operations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockStore)(nil).Batch), operations)
}

// Close mocks base method.
func (m *MockStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStore)(nil).Close))
}

// Delete mocks base method.
func (m *MockStore) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), key)
}

// Flush mocks base method.
func (m *MockStore) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockStoreMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockStore)(nil).Flush))
}

// Get mocks base method.
func (m *MockStore) Get(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), key)
}

// GetBulk mocks base method.
func (m *MockStore) GetBulk(keys ...string) ([][]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBulk", varargs...)
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulk indicates an expected call of GetBulk.
func (mr *MockStoreMockRecorder) GetBulk(keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulk", reflect.TypeOf((*MockStore)(nil).GetBulk), keys...)
}

// GetTags mocks base method.
func (m *MockStore) GetTags(key string) ([]storage.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTags", key)
	ret0, _ := ret[0].([]storage.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockStoreMockRecorder) GetTags(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockStore)(nil).GetTags), key)
}

// Put mocks base method.
func (m *MockStore) Put(key string, value []byte, tags ...storage.Tag) error {
	m.ctrl.T.Helper()
	varargs := []any{key, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockStoreMockRecorder) Put(key, value any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockStore)(nil).Put), varargs...)
}

// Query mocks base method.
func (m *MockStore) Query(expression string, options ...storage.QueryOption) (storage.Iterator, error) {
	m.ctrl.T.Helper()
	varargs := []any{expression}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(storage.Iterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockStoreMockRecorder) Query(expression any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{expression}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockStore)(nil).Query), varargs...)
}
