// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/czh0526/aries-framework-go/pkg/didcomm/common/service (interfaces: Messenger,MessengerHandler)
//
// Generated by this command:
//
//	mockgen -destination pkg/internal/gomocks/didcomm/common/service/mocks.gen.go -self_package mocks -package mocks github.com/czh0526/aries-framework-go/pkg/didcomm/common/service Messenger,MessengerHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	service "github.com/czh0526/aries-framework-go/pkg/didcomm/common/service"
	gomock "go.uber.org/mock/gomock"
)

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
	isgomock struct{}
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// ReplyTo mocks base method.
func (m *MockMessenger) ReplyTo(msgID string, msg service.DIDCommMsgMap, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msgID, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyTo", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyTo indicates an expected call of ReplyTo.
func (mr *MockMessengerMockRecorder) ReplyTo(msgID, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msgID, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyTo", reflect.TypeOf((*MockMessenger)(nil).ReplyTo), varargs...)
}

// ReplyToMsg mocks base method.
func (m *MockMessenger) ReplyToMsg(in, out service.DIDCommMsgMap, myDID, theirDID string, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{in, out, myDID, theirDID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyToMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyToMsg indicates an expected call of ReplyToMsg.
func (mr *MockMessengerMockRecorder) ReplyToMsg(in, out, myDID, theirDID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{in, out, myDID, theirDID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyToMsg", reflect.TypeOf((*MockMessenger)(nil).ReplyToMsg), varargs...)
}

// Send mocks base method.
func (m *MockMessenger) Send(msg service.DIDCommMsgMap, myDID, theirDID string, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msg, myDID, theirDID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMessengerMockRecorder) Send(msg, myDID, theirDID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, myDID, theirDID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessenger)(nil).Send), varargs...)
}

// SendToDestination mocks base method.
func (m *MockMessenger) SendToDestination(msg service.DIDCommMsgMap, sender string, destination *service.Destination, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msg, sender, destination}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendToDestination", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToDestination indicates an expected call of SendToDestination.
func (mr *MockMessengerMockRecorder) SendToDestination(msg, sender, destination any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, sender, destination}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToDestination", reflect.TypeOf((*MockMessenger)(nil).SendToDestination), varargs...)
}

// MockMessengerHandler is a mock of MessengerHandler interface.
type MockMessengerHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerHandlerMockRecorder
	isgomock struct{}
}

// MockMessengerHandlerMockRecorder is the mock recorder for MockMessengerHandler.
type MockMessengerHandlerMockRecorder struct {
	mock *MockMessengerHandler
}

// NewMockMessengerHandler creates a new mock instance.
func NewMockMessengerHandler(ctrl *gomock.Controller) *MockMessengerHandler {
	mock := &MockMessengerHandler{ctrl: ctrl}
	mock.recorder = &MockMessengerHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessengerHandler) EXPECT() *MockMessengerHandlerMockRecorder {
	return m.recorder
}

// HandleInbound mocks base method.
func (m *MockMessengerHandler) HandleInbound(msg service.DIDCommMsgMap, ctx service.DIDCommContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleInbound", msg, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleInbound indicates an expected call of HandleInbound.
func (mr *MockMessengerHandlerMockRecorder) HandleInbound(msg, ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleInbound", reflect.TypeOf((*MockMessengerHandler)(nil).HandleInbound), msg, ctx)
}

// ReplyTo mocks base method.
func (m *MockMessengerHandler) ReplyTo(msgID string, msg service.DIDCommMsgMap, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msgID, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyTo", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyTo indicates an expected call of ReplyTo.
func (mr *MockMessengerHandlerMockRecorder) ReplyTo(msgID, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msgID, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyTo", reflect.TypeOf((*MockMessengerHandler)(nil).ReplyTo), varargs...)
}

// ReplyToMsg mocks base method.
func (m *MockMessengerHandler) ReplyToMsg(in, out service.DIDCommMsgMap, myDID, theirDID string, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{in, out, myDID, theirDID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyToMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyToMsg indicates an expected call of ReplyToMsg.
func (mr *MockMessengerHandlerMockRecorder) ReplyToMsg(in, out, myDID, theirDID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{in, out, myDID, theirDID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyToMsg", reflect.TypeOf((*MockMessengerHandler)(nil).ReplyToMsg), varargs...)
}

// Send mocks base method.
func (m *MockMessengerHandler) Send(msg service.DIDCommMsgMap, myDID, theirDID string, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msg, myDID, theirDID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMessengerHandlerMockRecorder) Send(msg, myDID, theirDID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, myDID, theirDID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMessengerHandler)(nil).Send), varargs...)
}

// SendToDestination mocks base method.
func (m *MockMessengerHandler) SendToDestination(msg service.DIDCommMsgMap, sender string, destination *service.Destination, opts ...service.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{msg, sender, destination}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendToDestination", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToDestination indicates an expected call of SendToDestination.
func (mr *MockMessengerHandlerMockRecorder) SendToDestination(msg, sender, destination any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg, sender, destination}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToDestination", reflect.TypeOf((*MockMessengerHandler)(nil).SendToDestination), varargs...)
}
